# Change these first
owner: teknepal # Your GitHub organization or username, where this repository lives
repo: AGR-Status # The name of this repository

sites:
  - name: RGE
    url: https://www.rge.com
  - name: CMP
    url: https://cmpco.com
  - name: NYSEG
    url: https://www.nyseg.com
  - name: UI
    url: https://uinet.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /AGR-Status
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AGR-Status
  introTitle: "AGR STATUS"
  introMessage: test
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
